/*
 * Copyright (c) Fiorano Software Pte. Ltd. and affiliates. All rights reserved. http://www.fiorano.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package com.fiorano.openesb.microservice.launch.impl;

public interface EventStateConstants
{
    //SERVICE STATE CONSTANTS
    /**
     *  Constant defining the state for success of service fetch process.
     */
    public final static String COMPONENT_NOT_LICENSED = "COMPONENT_NOT_LICENSED";

    /**
     *  Constant defining the state for failure of service fetch process.
     */
    public final static String SERVICE_FETCH_FAILED = "COMPONENT_FETCH_FAILED";

    /**
     *  Constant defining the state for success of service fetch process.
     */
    public final static String SERVICE_FETCH_SUCCESS = "COMPONENT_FETCH_SUCCESS";

    /**
     *  Constant defining the state that service fetch is not required. This is used in case component's launch type is NONE.
     */
    public final static String SERVICE_FETCH_NOT_REQUIRED = "COMPONENT_FETCH_NOT_REQUIRED";

    /**
     *  Constant defining the state for failure of service launch process.
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_FAILED_TO_LAUNCH = "SERVICE_FAILED_TO_LAUNCH";

    /**
     *  Constant defining the state for failure of service kill process.
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_FAILED_TO_KILL = "SERVICE_FAILED_TO_KILL";

    /**
     *  Constant defining the state for service getting synchronized.
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_SYNCHRONIZED = "SERVICE_SYNCHRONIZED";

    /**
     *  Constant defining the state for failure of service synnchronization
     *  process.
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_FAILED_TO_SYNCHRONIZE = "SERVICE_FAILED_TO_SYNCHRONIZE";

    /**
     *  Constant
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_KILLED_ON_TPS_SHUTDOWN = "SERVICE_KILLED_ON_TPS_SHUTDOWN";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_HANDLE_CREATED = "SERVICE_HANDLE_CREATED";

    /**
     *  Description of the Field
     */
    public final static String SP_SERVICE_HANDLE_CREATED = "SP_SERVICE_HANDLE_CREATED";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_HANDLE_BOUND = "SERVICE_HANDLE_BOUND";

      public final static String SERVICE_HANDLE_BOUNDING = "SERVICE_HANDLE_BOUNDING";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_HANDLE_UNBOUND = "SERVICE_HANDLE_UNBOUND";
    /**
     *  The component is stopped and unbound event is generated.The fes specially asks a peer to stop a component when
     *  multiple instances of an applications component are detected over the network. To have only one instance ,certain peers
     *  are asked to stop their instances so that only one peer hosts the component. The consequence of this is that a unbound event is generated by peer so studio
     *  shows the component as red.Since these actions of the fes are part of internal management the rtl should not get them. 
     * @since Tifosi2.0
     */
    public final static String SERVICE_HANDLE_UNBOUND_SERVER_MANAGEMENT_ACTION = "SERVICE_HANDLE_UNBOUND_SERVER_MANAGEMENT_ACTION";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_HANDLE_DESTROYED = "SERVICE_HANDLE_DESTROYED";

    public final static String SERVICE_KILL_REQUEST = "SERVICE_KILL_REQUEST";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String LAUNCH_CALL_IN_PROGRESS = "LAUNCH_CALL_IN_PROGRESS";

    // APPLICATION STATE CONSTANTS
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_LAUNCHED = "APPLICATION_LAUNCHED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_LAUNCH_STARTED = "APPLICATION_LAUNCH_STARTED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_KILLED = "APPLICATION_KILLED";

    /**
     * Enterprise Server will ask the reconnected peer to remove all its event process handles if they should not be present according to server
     * as part of the server management action. The resulting event generated should not cause client to show the Application as stopped if the
     * server has already mandated another peer to run the aforementioned application
     */
    public final static String APPLICATION_HANDLE_REMOVED_SERVER_MANAGEMENT_ACTION = "APPLICATION_HANDLE_REMOVED_SERVER_MANAGEMENT_ACTION";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_SYNCHRONIZED = "APPLICATION_SYNCHRONIZED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_CREATED = "APPLICATION_CREATED";

    /**
     *  Description of the Field
     */
    public final static String APPLICATION_FAILED_TO_SYNCHRONIZE = "APPLICATION_FAILED_TO_SYNCHRONIZE";

    // FPS STATE CONSTANTS
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String TIFOSI_SERVER_LAUNCHED = "TIFOSI_SERVER_LAUNCHED";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String TIFOSI_SERVER_SHUTDOWN = "TIFOSI_SERVER_SHUTDOWN";

    //  FPS Unavailable (cable problem ?)
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String TIFOSI_SERVER_UNAVAILABLE = "TIFOSI_SERVER_UNAVAILABLE";

    /**
     * A new FPS has been added.
     */
    public final static String NEW_TIFOSI_SERVER_CONFIGURED = "NEW_TIFOSI_SERVER_CONFIGURED";

    //  FPS Re-available [cable problem solved :-)]
    /**
     *  Description of the Field
     */
    public final static String TIFOSI_SERVER_AVAILABLE = "TIFOSI_SERVER_AVAILABLE";

    /**
     *  P2P Connection has got broken between two FPS.
     */
    public final static String P2P_CONNECTION_BROKEN = "P2P_CONNECTION_BROKEN";

    /**
     *  P2P Connection has been established between two FPS.
     */
    public final static String P2P_CONNECTION_ESTABLISHED = "P2P_CONNECTION_ESTABLISHED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String TIFOSI_SERVER_APPLICATION_INFO = "TIFOSI_SERVER_APPLICATION_INFO";

    /**
     *  id for ping event
     *
     * @since Tifosi2.0
     */
    public final static String TIFOSI_SERVER_PING = "TIFOSI_SERVER_PING";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_PROVIDER_STARTED = "SERVICE_PROVIDER_STARTED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_PROVIDER_SHUTDOWN = "SERVICE_PROVIDER_SHUTDOWN";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String MESSAGE_BUS_CONNECTION_FAILURE = "MESSAGE_BUS_CONNECTION_FAILURE";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String RECONNECTED_TO_MESSAGE_BUS = "RECONNECTED_TO_MESSAGE_BUS";

    public final static String JMS_STATE_CHANGED = "JMS_STATE_CHANGED";

    //SBW SPECIFIC EVENT STATES
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String OUT_PORT_STATE_TRAVERSED = "OUT_PORT_STATE_TRAVERSED";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String IN_PORT_STATE_TRAVERSED = "IN_PORT_STATE_TRAVERSED";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_STATE_TRAVERSED = "SERVICE_STATE_TRAVERSED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_TRACE_MESSAGE = "SERVICE_TRACE_MESSAGE";
    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String APPLICATION_FAILED_TO_PREPARE_FOR_LAUNCH = "APPLICATION_FAILED_TO_PREPARE_FOR_LAUNCH";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String SERVICE_CURRENTLY_BEING_FETCHED = "SERVICE_CURRENTLY_BEING_FETCHED";

    /**
     *  Description of the Field
     *
     * @since Tifosi2.0
     */
    public final static String PERSISTENT_SERVICES_LAUNCHED_ON_TPS = "PERSISTENT_SERVICES_LAUNCHED_ON_TPS";

    public final static String SERVICE_DEPLOYMENT_REQUEST = "SERVICE_DEPLOYMENT_REQUEST";

    public final static String CREATE_ACL_REQUEST = "CREATE_ACL_REQUEST";

    public final static String APPLICATION_EDIT_REQUEST = "APPLICATION_EDIT_REQUEST";
    public final static String APPLICATION_VIEW_REQUEST = "APPLICATION_VIEW_REQUEST";
    public final static String APPLICATION_SYNCHRONIZE_REQUEST = "APPLICATION_SYNCHRONIZE_REQUEST";
    public final static String APPLICATION_KILL_REQUEST = "APPLICATION_KILL_REQUEST";
    public final static String APPLICATION_LAUNCH_REQUEST = "APPLICATION_LAUNCH_REQUEST";
    public final static String APPLICATION_PREPARE_LAUNCH_REQUEST = "APPLICATION_PREPARE_LAUNCH_REQUEST";
    public final static String CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

    public final static String APPLICATION_SAVED = "APPLICATION_SAVED";
    public final static String APPLICATION_RENAMED = "APPLICATION_RENAMED";

    public final static String SERVICE_LAUNCH_REQUEST = "SERVICE_LAUNCH_REQUEST";

    public final static String TPS_LOGIN_REQUEST = "TPS_LOGIN_REQUEST";
    public final static String SP_LOGIN_REQUEST = "SP_LOGIN_REQUEST";
    public final static String DISK_USAGE = "DISK_USAGE";

    public final static String QUEUE_LIMIT_EXCEEDED = "QUEUE_LIMIT_EXCEEDED";
    public final static String DISCONNECTED_FROM_JMS = "DISCONNECTED_FROM_JMS";
    public final static String CONNECTED_TO_JMS = "CONNECTED_TO_JMS";

    public final static String TPS_CONFIGURATION_SUCCESSFUL = "TPS_CONFIGURATION_SUCCESSFUL";
    public final static String TPS_CONFIGURATION_NOT_SUCCESSFUL = "TPS_CONFIGURATION_NOT_SUCCESSFUL";

    // OnEvent() FPS gets its configs from
    public final static String INITIATE_CONFIGURATION_FETCH = "INITIATE_CONFIGURATION_FETCH";

    public final static String INITIATE_CONFIGURATION_NO_FETCH = "INITIATE_CONFIGURATION_NO_FETCH";

    //added by Pushkar for raising event for DB connection status
    public final static String DB_CONNECTION_UP = "DB_CONNECTION_UP";
    public final static String DB_CONNECTION_DOWN = "DB_CONNECTION_DOWN";

    public final static String SET_ACL_REQUEST = "SET_ACL_REQUEST";
    public static final String APPLICATION_REPOSITORY_UPDATION = "APPLICATION_REPOSITORY_UPDATION";
    public static final String APPLICATION_DELETED = "APPLICATION_DELETED";
    public static final String APPLICATION_SYNCHRONIZE_STARTED = "APPLICATION_SYNCHRONIZED_STARTED";
    public static final String ROUTE_DEBUGGER_SET = "ROUTE_DEBUGGER_SET";
    public static final String ROUTE_DEBUGGER_REMOVED = "ROUTE_DEBUGGER_REMOVED";
    public static final String APPLICATION_STATE_RESTORED = "APPLICATION_STATE_RESTORED";
    public static final String TIFOSI_SERVER_ACTIVE = "TIFOSI_SERVER_ACTIVE";
    public static final String TIFOSI_SERVER_WAITING = "TIFOSI_SERVER_WAITING";
    public static final String TIFOSI_SERVER_STANDALONE = "TIFOSI_SERVER_STANDALONE";
    public static final String TIFOSI_SERVER_PASSIVE = "TIFOSI_SERVER_PASSIVE";
    public final static String TIFOSI_SERVER_ACTIVE_SYNC = "TIFOSI_SERVER_ACTIVE_SYNC";
    public final static String TIFOSI_SERVER_SYNC_STATUS = "TIFOSI_SERVER_SYNC_STATUS";
    public final static String TIFOSI_SERVER_PASSIVE_SYNC = "TIFOSI_SERVER_PASSIVE_SYNC";
    public final static String TIFOSI_SERVER_HA_PEER_CONNECTED = "TIFOSI_SERVER_HA_PEER_CONNECTED";
    public final static String TIFOSI_SERVER_RECONNECTED = "TIFOSI_SERVER_RECONNECTED";

    //APIManagement
    public final static String API_PROJECT_DEPLOYED = "API_PROJECT_DEPLOYED";
    public final static String API_PROJECT_UNDEPLOYED = "API_PROJECT_UNDEPLOYED";
    public final static String API_PROJECT_CREATED = "API_PROJECT_CREATED";
    public final static String API_PROJECT_DELETED = "API_PROJECT_DELETED";


}
