Fiorano Microservices and Servers can be deployed in Docker containers running on different systems. Microservices can be deployed in the same Docker container as the server or as a different Docker container.

![](https://github.com/prathew/Fiorano-Microservice-Platform/blob/master/Fiorano.Docker.png)

Microservices deployed in different containers communicate among one another using JMS. Microservices deployed in a different docker container exchange control and status information using a custom wire protocol (CCP) built on top of JMS. The Dockerfile necessary for the creation of Docker image corresponding to a microservice instance is automatically generated by the tool.

**How Fiorano Complements Docker?**

| Docker | Fiorano |
| ------ | ------- |
| Docker is mostly focused on deployment of Microservices and their dependencies | Fiorano includes Microservice-development, interaction-definition, deployment, and monitoring |
| Docker does not handle communication between Microservices. | Fiorano uses JMS for asynchronous messaging between Microservices |
| Docker does not provide a birds eye view of a solution. It is impossible to visualize the interactions between Microservices | Fiorano eStudio resolves all these issues |
| Monitoring is limited to system stats of various containers deployed | Comprehensive monitoring at microservice, application, and system level |
| Data-loss on failure is not handled by each individual Microservice | Fiorano ESB/Container ensures zero data-loss: restart where you stopped, inbuilt, real-time high-availability |
